#!/bin/bash -e

container=container-tools-$RANDOM
image=vpartington/container-tools
red="\\033[0;31m"

while getopts "h:" opt; do
  case "$opt" in
  h)  hostname=$OPTARG ;;
  \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
  :) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
  *) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
  esac
done
shift $((OPTIND -1))

[ -z $hostname ] && echo -e "${red}Provide the hostname of the node with the -h flag" && exit 1

IFS='' overrides=$(cat <<EOF
{
    "spec": {
        "containers": [
            {
                "stdin": true,
                "tty": true,
                "args": [ "bash" ],
                "name": "$container",
                "image": "$image",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/docker.sock",
                        "name": "dockersocket"
                    }
                ]
            }
        ],
        "volumes": [
            {
                "name": "dockersocket",
                "hostPath": {
                    "path": "/var/run/docker.sock"
                }
            }
        ],
        "nodeSelector":
        {
            "kubernetes.io/hostname": "$hostname"
        }
    }
}
EOF
)

kubectl run $container --image=$image --rm --stdin --tty bash --overrides=$overrides
